from Class_module_FishBox import *
#创建大盒子实例，并进行相关运算
bigbox=FishBox(60,30,40)
bigbox.price=1000
bigbox.capacity=20
bigbox.weight=10
print('大礼盒的体积为%d'%(bigbox.volume()))
print('大礼盒的表面积为%d'%(bigbox.area()))
index=bigbox.type.index('大礼盒')
#index()函数为在列表、元组中返回下标，见课本P56
bigboxnums=bigbox.countBoxNums(200,index)
print('200条鱼需要%d个大礼盒'%(bigboxnums))
print('200条鱼的总价格是%d'%(bigbox.total(bigboxnums,bigbox.price)))
print('=========================')
#创建小盒子实例，并进行相关运算
smallbox=FishBox(50,20,30)
smallbox.capacity=10
smallbox.weight=5
print('小礼盒的体积为%d'%(smallbox.volume()))
print('小礼盒的表面积为%d'%(smallbox.area()))
index=smallbox.type.index('小礼盒')
smallboxnums=smallbox.countBoxNums(200,index)
print('200条鱼需要%d个小礼盒'%(smallboxnums))
print('200条鱼的总价格是%d'%(bigbox.total(smallboxnums,smallbox.price)))
print('==========================')
print(issubclass(FishBox,Box2))
print(issubclass(Box2,Box1))
print(issubclass(FishBox,Box1))
#确认FishBox、Box2和Box1三个类的父子关系
